run-name: Build project

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - "Build-script-package-bump"
  workflow_dispatch: {}

env:
  MAJOR_RELEASE_NR: 0
  MINOR_OFFSET: 0

jobs:
  release-project:
    name: Release game builds
    runs-on: ubuntu-latest
    needs: buildForAllSupportedPlatforms
    steps: 
      - name: run number with offset
        env:
          NUM: ${{ github.run_number }}
        run: echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM - $MINOR_OFFSET))" >> $GITHUB_ENV
      - run: echo $GITHUB_RUN_NUMBER_WITH_OFFSET
    
      - name: Get repo files
        uses: actions/download-artifact@v3
        with:
          path: build

      - name: Zipping win
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build/StandaloneWindows64.zip build/StandaloneWindows64
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.MAJOR_RELEASE_NR }}.${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          name: Release V${{ env.MAJOR_RELEASE_NR }}.${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/StandaloneWindows64.zip

  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targetPlatform }}
          path: build